name: My workflow
on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Hellow World Action
    runs-on: ubuntu-latest

    steps:
    - run: |
       echo "Hello Wolrd"
