name: My workflow
on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Hellow World Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
      name: Checkout
    - uses: nyurik/action-setup-nginx@v1.1
      name: Installing nginx
    - run: |
        cp index.html /usr/share/nginx/html
    - run: |
        service nginx restart
